# 18.06 Spring2019 pset 2 
## due Wednesday  2/20 at 10:55am

Note about pedagogical style: Your professor tends to use the technique of "foreshadowing."  This means that you may see a notion in the homework that we believe you are ready to attack at this point in the class,  but the bigger picture emerges later. It is well known that most students learn best this way.  Of course if you start googling around, you can see the bigger picture earlier, at least with some other author's notation or point of view.  I can't and wouldn't stop you, but rest assured you will see concepts over and over again in expanding waves in this class. <br> <br>
If you need to know where we are heading, I am planning to cover all of the results (but not the methods in) Strang's chapters 2 and 3 by leading up to the SVD (singular value decomposition) without any mention of pivot variables, free variables, or eigenvalues.  This means you are less likely to understand how to hand compute the various concepts, and more likely to understand them conceptually.  This gives us time to also show you some applications.  It is indeed an experiment, which is why I welcome feedback, positive and negative, during my many, office hours, but I honestly feel in my heart that I am providing a valuable approach.
<br><br>
The problem sets are meant to be learning experiences, and perhaps more challenging than you are familiar with.  This is not going to be the style of class where you find a similar problem in the lecture notes and just repeat.  You may have to reach back into the 18.02 prerequisites for this class.  You may learn a lot by working with other students in the class.  There is a lot to be learned  [at the math learning center](https://math.mit.edu/learningcenter/), in recitations, during the TAs office hours, and my numerous office hours.  No promises that 18.06 is easy, only that you will learn a lot!

All questions are 10 points, problem 10 will be a freebie if you execute it. (Coming soon)

### 1. Warmup questions  (10 points, -1 for wrong answers until 0 is reached)
   Reminder: in mathematical contexts the distinction between an n-vector and an nx1 single column matrix tends to be blurred.  On computers this can and does cause problems.  In the following, we will blur the distinction. For these problems, some of you will know how to do it from the prerequisites, some will ask your friends or your recitation instructor, but in any event you will strengthen your general feel for linear algebra.<br> 
    Some places worth looking for answers are Strang Section 1.2, page 194, VMLS page 58.  The definition of a [normal](https://en.wikipedia.org/wiki/Normal_(geometry)), the definition of a [gradient](https://www.khanacademy.org/math/multivariable-calculus/multivariable-derivatives/partial-derivative-and-gradient-articles/a/the-gradient), the definition of a [plane](http://mathworld.wolfram.com/Plane.html) and the definition of a [hyperplane](http://mathworld.wolfram.com/Hyperplane.html) which generalizes a plane. Also ||v|| = sqrt(vᵀv), is the length of a vector v, sometimes pronounced the norm of v, or the magnitude of v.  
   
   
   
   
       1a. If vᵀw=0 we say that v and w are a) perpendicular b) orthogonal c) at right angles d) all the above.
       1b. The equation 2x+3y+4z = 0 describes a a) line  b)  plane through 0  c)  plane not through 0 d) sphere
       1c. A normal to your answer in 1b is __________?
       1d. The equation 2x+3y+4z = 2019 describes a a) line  b)  plane through 0  c)  plane not through 0 d) sphere
       1e. A normal to your answer in 1d is __________?
       1f. The equation x²+y²+z²=1 describes a a) line  b)  plane through 0  c)  plane not through 0 d) sphere
       1g. A normal to your answer in 1f is __________?  (Hint: ok to use intuition from two or three dimensions)
       1h. Calculate the gradient of f(x,y,z) = 2x+3y+4z
       1i. Calculate the gradient of f(x,y,z) = x²+y²+z² 
       1j. The inequality 2x+3y+4 > 0 describes a region of 3 dimensional space.  Describe that region:_____
       1k. The inequality 2x+3y+4 < 2019 describes a region of 3 dimensional space.  Describe that region:_____
       1l.  Using vector language in Rⁿ, (no elements or indices)  write an equation that describes every v on the hyperplane through 0 with given normal vector w (not 0).  
       1m. Give an example of a hyperplane parallel to the hyperplane in 1l above that does  not go through 0.
       1n. Suppose given a nonzero w that we consider the hyperplane of all v for which  wᵀv=1.  Find the unique vector v (in terms of w) that is on this hyperplane in the direction w.  (It is helpful to define ||w|| as the length of w.) 

       

1a) d
(v^T)w is the definition of a dot product, and the dot product of two vectors is 0 iff they are perpendicular. "Perpendicular," "orthogonal," and "at right angles" are all synonyms.

1b) b

1c) The normal vector to the equation 2x+3y+4z=0 is the vector <2,3,4>, since the equation for a line is defined by <normal vector>*<x,y,z>

1d) c

1e) The normal vector to the equation is also <2,3,4>

1f) d

1g) The normal vector of the sphere is <x, y, z>

1h) <2, 3, 4>

1i) <2x, 2y, 2z>

1j) The inequality describes the region directly above the plane defined by 2x+3y+4 = 0 (or 2x+3y+4z > 0 as I assume was originally intended)

1k) The inequality descibes the region directly below the plane defined by 2x+3y+4 = 2019 (or 2x+3y+4z < 2019 as I assume was originally intended)

1l) w^T x = 0

1m) w^T x = 1

1n) The unique vector v such that v^T w = 1 and v is parallel to w is v = w / ||w||

## 2. (Real) Vector Spaces (10 points) (Strang page 123, Lecture 2 slides)

a) If $v$ is a vector in any vector space, what is the complete list of vectors that must also be in this vector space?

b) Must a vector space contain a zero vector?  Why?

c) What is the zero vector in $R^4$? in $R^{2,3}$? What is the zero function?  What is the zero  (differential) operator from functions to functions? (Hint: The zero  operator takes in an arbitrary function and returns....)

d) State in words the difference between the zero function and the zero operator, as they seem so similar.

### Response

a) For $v \in \mathbb{V}$, the complete list of vectors in this vector space is $\forall a \in \mathbb{R}, av \in \mathbb{V}$ if multiplication is defined. 

b) A vector space must contain a zero vector because any vector in the vector space must be closed in multiplication by a scalar, which includes the scalar 0. It must also be closed in addition, which includes the negative vector. 

c) The zero vector in $\mathbb{R}^4$ is (0,0,0,0). 

The zero vector in $\mathbb{R}^{2,3}$ is $ \begin{pmatrix} 0 & 0 & 0 \\ 0 & 0 & 0 \end{pmatrix}$,

The zero function in $\mathbb{R}^4$ is $f(v) = \begin{pmatrix} 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 \end{pmatrix}$v, 

The zero function in $\mathbb{R}^{2,3}$ is $f(B) = \begin{pmatrix} 0 & 0  \\ 0 & 0  \end{pmatrix}B$

The zero operator in $\mathbb{R}^4$ is $\begin{pmatrix} 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 \end{pmatrix}$

The zero operator in $\mathbb{R}^{2,3}$ is $\begin{pmatrix} 0 & 0  \\ 0 & 0  \end{pmatrix}$

d) A zero function maps any vector in one vector space to the zero vector in another vector space (possibly the same vector space), whereas a zero operator maps any function to a zero function.

## 3. Am I a vector space?  (The basic question here is whether every linear combination is in the space.  If there is no zero, then I'm for sure not a vector space.)

a) All vectors in $R^n$ whose entries sum to 0.

b) All matrices in $R^{m,n}$ whose entries when squared sum to 1.

c) Cubic polynomials of the form $f(x) = a + bx + cx^2 + dx^3$, where $a,b,c,d$ are abitrary, possibly 0.

d) All linear functions of the form $f(x) = mx +b$, where $f(17)=0$. ($m$ or $b$ may possibly be 0)

e)  All linear functions of the form $f(x) = mx +b$, where $f(0)=17$.($m$ or $b$ may possibly be 0)

a) Yes

b) No

c) Yes

d) Yes

e) No

## 4. Nullspace

A fact you are supposed to already know about matrices is that $M(cv+dw) = cMv+dMw$, if $M$ is any matrix, $c$ and $d$ are any scalars, and $v$ and $w$ are any vectors.  

Suppose for some particular rectangular matrix $M$, we have $Mv=0$ and $Mw=0$ for some particular vectors $v$ and $w$.  Is it true that if $x$ is a linear combination of $v$ and $w$ then $Mx$ is also 0? Why?

The set of vectors $x$ for which $Mx=0$ is known as the nullspace of $X$.  For an mxn matrix it could be the zero vector in $R^n$ or it could be all of $R^n$.

What is the nullspace of the $n$ by $n$ identity matrix?  The $n$ by $n$ zero matrix?  The $m$ by $n$ matrix of all ones?

### Response

Given the fact that for any matrix $M$, scalars $c$ and $d$, and vectors $v$ and $w$: $M(cv+dw) = cMv+dMw$.

For some matrix $M$ and vectors $v$, $w$, and $x$, where $x$ is a linear combination $v$ and $w$, we can conclude that $Mx=0$. This is because we can represent $x$ as $cv+dw$ for some c and d. We can then substitute this expression in place of $x$ to get:

$\begin{align*}
Mx &= 0 \\
M(cv+dw) &= 0 \\
cMv+dMw &= 0 \\
c(0) + d(0) &= 0 \\
0 &= 0
\end{align*}$

Therefore we can conclude that the matrix M multiplied by any linear combination of $v$ and $w$ would also equal 0.


The nullspace of an $n\times n$ identity matrix is the zero vector in $\mathbb{R}^{n}$.

The nullspace of an $n\times n$ zero matrix is all vectors in $\mathbb{R]^n$.

The nullspace of an $m\times n$ matrix of all ones is any vector in $\mathbb{R}^n$ whose elements sum to 0.

## 5. Column Space

The column space of a matrix $M$ is the set of all vectors $y$ which can be written in the form $Mx$ for some vector $x$.  Why is the column space a vector space?

What is the column space of the $n$ by $n$ identity matrix?  The $n$ by $n$ zero matrix?  The $m$ by $n$ matrix of all ones?


### Response

The column space of the matrix $M$ is a vector space because the column space is the set of all vectors that are a linear combination of the columns of the matrix $M$. All vector spaces can be represented as a linear combination of vectors.

The columns space of an $n\times n$ identity matrix is all vectors in space $\mathbb{R}^n$.

The columns space of an $n\times n$ zero matrix is the zero vector in $\mathbb{R}^n$.

The columns space of an $m\times n$ matrix of all ones is a line in $\mathbb{R}^m$ with a slope of a vector with all 1s going through the origin. 

## 6. Using the SVD



In [1]:
using LinearAlgebra

In Julia if you are given an m x n matrix $A$, Julia returns a matrix $U$, a vector $s$ and a Matrix $V$ for which  A = U * Diagonal(s) * V' (up to floating point roundoff errors) <br>

If m >n,  $U$ is m by n, Diagonal(s) is n by n,  and $V$ is n by n. <br>
If m < n $U$ is m by m, Diagonal(s) is m by m, and $V$ is n by m.

You can remember this because the result is m by n, and the Diagonal(s) is always square whose size is the smaller of m and n.

Here are some examples:


In [2]:
A = rand(4,5)
U,s,V = svd(A)
println( size(U), size(Diagonal(s)), size(V))

(4, 4)(4, 4)(5, 4)


In [3]:
A = rand(5,4)
U,s,V = svd(A)
println( size(U), size(Diagonal(s)), size(V))

(5, 4)(4, 4)(4, 4)


What are the sizes of $U$, $Diagonal(s)$ and $V$ for <br>
    a) A 10x10 matrix? <br>
    b) A 10x20 matrix? <br>
    c) A 20x10 matrix?

### Response

(10,10), (10,10), (10, 10)

(10, 10), (10, 10), (20, 10)

(20, 10), (10, 10), (10, 10)

## 7. It is possible to solve Ax=b for an invertible A using the svd. It's slightly less efficient than LU but usually quite reasonably accurate, even at least as accurate as LU.

Here is an example from Svetlana's problems posted in Piazza:

x + 2y + 3z =1 <br>
y + z = 2 <br>
3x + y - z =3

Solution:


In [4]:
# Form the Matrix
A = [1 2 3; 0 1 1; 3 1 -1]

3×3 Array{Int64,2}:
 1  2   3
 0  1   1
 3  1  -1

In [5]:
# For the right hand side b
b = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [6]:
U,s,V = svd(A)
V*((U'b)./s)

3-element Array{Float64,1}:
 -1.0000000000000004
  4.000000000000002 
 -1.9999999999999998

Don't let floating point fool you, the answer given is -1,4,-2.  Check that the solution is right.  Explain mathematically why V*((U'b)./s) gives the right answer.

On an exam, you will not be expected to compute an SVD using eigenvalues or a computer.  The SVD story will unfold during the course of the semester.

### Response

The singular value decomposition of a matrix $M \in \mathbb{R}^{m,n}$ results in an orthogonal matrix $U$, a diagonal matrix $s$, and another orthogonal matrix $V$. To solve for $x$ in the equation $Ax=b$, we can take advantage of the orthogonality and multiply by the transpose of the matrices and "divide" element-wise by the diagonal matrix to solve for x.

## 8.  Suppose $W$ is an unknown 2x2 matrix, and we want to approximately find a $W$ that best fits $Wxᵢ=yᵢ$ where x₁,x₂,x₃,y₁,y₂,y₃ are each known 2 vectors?  How would you find $W$ using QR?
Hint: this is tricky because the unknowns are the four elements in $W$.  I think this problem is hard.

### Response



We begin by defining the relationship between W, X and Y.
We define $W$ to be: $$W=\begin{pmatrix} w_{1,1} & w_{1,2} \\ w_{1,1} & w_{1,2}  \end{pmatrix} $$
First, we define X to be a matrix with columns of $x_i$.
$$X = \begin{pmatrix} x_1 & x_2 & x_3 \end{pmatrix} = 
\begin{pmatrix} x_{1,1} & x_{1,2} & x_{1,3} \\ x_{2,1} & x_{2,2} & x_{2,3}\end{pmatrix}$$
Next, we define Y to be a matrix with columns of $y_i$.
$$Y = \begin{pmatrix} y_1 & y_2 & y_3 \end{pmatrix} = 
\begin{pmatrix} y_{1,1} & y_{1,2} & y_{1,3} \\ y_{2,1} & y_{2,2} & y_{2,3}\end{pmatrix}$$
We can redefine the relationship then to be:
$$WX=Y$$

We can rearrange this relationship to be a different but true equation:
$$\begin{pmatrix} x_{1,1} & x_{1,2} & 0 & 0 \\ 0 & 0 & x_{1,1} & x_{1,2} \\x_{2,1} & x_{2,2} & 0 & 0 \\ 0 & 0 & x_{2,1} & x_{2,2} \\x_{3,1} & x_{3,2} & 0 & 0 \\ 0 & 0 & x_{3,1} & x_{3,2} \end{pmatrix}\begin{pmatrix} w_{1,1} \\ w_{1,2} \\ w_{2,1} \\ w_{2,2} \end{pmatrix}=\begin{pmatrix} y_{1,1} \\ y_{2,1} \\ y_{1,2} \\ y_{2,2} \\ y_{1,3} \\ y_{2,3}\end{pmatrix}$$

We then simply break down the first and third matrix into SVD factorization and solve for the values of $w_{1,1}, w_{1,2}, w_{2,1}, and w_{2,2}$

In [7]:
[1 0; 0 0; 0 1]*[2 1; 0 1]

3×2 Array{Int64,2}:
 2  1
 0  0
 0  1

 ## 9. A Permutation of n 
 is a rearrangement of the numbers 1 through n. Here is a random permutation of 1:5

In [8]:
using Random
p = randperm(5)

5-element Array{Int64,1}:
 5
 3
 1
 4
 2

A Permutation matrix is row reordering of the identity matrix

In [9]:
ident = Matrix{Int64}(I,5,5)

5×5 Array{Int64,2}:
 1  0  0  0  0
 0  1  0  0  0
 0  0  1  0  0
 0  0  0  1  0
 0  0  0  0  1

In [10]:
ident[p,:]

5×5 Array{Int64,2}:
 0  0  0  0  1
 0  0  1  0  0
 1  0  0  0  0
 0  0  0  1  0
 0  1  0  0  0

What is closest to the number of parameters that are needed for an n x n permutation matrix?
    a) n^2  b) n   c)n!  d)n^n

# 10. a Julia application of linear algebra
Understanding this code is not required for this class, but is an extra for those interested.  All of you might want to look just a little and execute the lines though.

 The signed distance to a hyperplane is one of those standard machine learning (and elsewhere!) codes.  In one commonly used notation, hyperplanes are written as the set of x for which θᵀx + θ₀ = 0 where θ is in Rⁿ and θ₀ is in R. The formula for the distance of a point p to this hyperplane is <br>
      distance =  (θᵀp +θ₀ )/||θ||

In [11]:
# Formula in Julia looks a lot like the math
d(p,θ,θ₀) = (θ'p .+ θ₀)/norm(θ)

# If you would like to annotate with types, this is also allowed
# this says p and θ must be vectors and θ₀ a number
d(p::Vector, θ::Vector, θ₀::Number) = (θ'p .+ θ₀)/norm(θ)

d (generic function with 2 methods)

In [12]:
n = 7
d( rand(n), rand(n), rand() )

1.4790037973998442

Python is a very popular language these days.  It is really nice to have lots of friends who know the same language.  Python suffers, however, from the two language problem:  that efficient machine learning code tends to use C or C++, and even numpy tends to mix metaphors being sort of python like and sort of something different. 

Are we above or below the hyperplane?

In [13]:
which_side(p,θ,θ₀) = d(p,θ,θ₀)<0 ? "I'm below" : "I'm above" # Ternary operator

which_side (generic function with 1 method)

In [14]:
which_side(randn(n), rand(n), rand() )

"I'm below"

What if we have a matrix of 5 data points, each column is in R^n?

In [15]:
P = randn(n,5)

7×5 Array{Float64,2}:
 -1.37854     0.796789    1.53984   -0.341609    1.58997 
  0.0657412   1.66258    -0.992653   0.827836   -0.72513 
 -0.188221   -1.03689    -2.39979   -0.468787    0.328374
  1.19954     0.0560223  -0.26057    1.00022     0.683436
  0.346487    1.41551    -1.35996    0.0145038  -0.551647
  0.65805     0.966625   -0.464763   1.01704    -0.274129
 -2.40222     0.978375   -0.851793  -0.807815    0.730587

In [16]:
distances = d( P, rand(n), rand() )  # Code evaluates five distances

1×5 Array{Float64,2}:
 -1.41395  2.34798  -1.25333  0.324758  1.04122

In [17]:
sign.(distances)  # elementwise sign function tells you above or below

1×5 Array{Float64,2}:
 -1.0  1.0  -1.0  1.0  1.0

Carrying around a θ and θ₀ separately seems silly.  How likely are you to remember that this is a pair next month?  Let's wrap them together:

In [18]:
struct Hyperplane
    θ  :: Vector
    θ₀ :: Number
end

In [19]:
h = Hyperplane( rand(3), rand() )

Hyperplane([0.915452, 0.294099, 0.405087], 0.9995382853053136)

In [20]:
dump(h)  # see what's inside

Hyperplane
  θ: Array{Float64}((3,)) [0.915452, 0.294099, 0.405087]
  θ₀: Float64 0.9995382853053136


Let's make it easy to write the more natural distance to a hyperplane function

In [21]:
d(p::Vector,  h::Hyperplane )  = d(p,h.θ,h.θ₀)

d (generic function with 3 methods)

In [22]:
h = Hyperplane( rand(n), rand() )
d( randn(n), h)

-1.1128557597343645

This professor encourages good coding, where mathemtical abstractions are wrapped with their names rather than being isolated as greek letters.

Let's generate a vector of 10 hyperplanes:

In [23]:
hyperplanes = [Hyperplane( rand(3), rand() ) for i=1:10 ]

10-element Array{Hyperplane,1}:
 Hyperplane([0.189505, 0.831027, 0.664038], 0.12456867876869482) 
 Hyperplane([0.108004, 0.175439, 0.145053], 0.873857285359878)   
 Hyperplane([0.893731, 0.710195, 0.730886], 0.12073429719640161) 
 Hyperplane([0.992766, 0.380624, 0.514421], 0.6250751841504534)  
 Hyperplane([0.448099, 0.453412, 0.743219], 0.7319981865935548)  
 Hyperplane([0.831305, 0.0047206, 0.111941], 0.8096815658326035) 
 Hyperplane([0.350493, 0.0648901, 0.831784], 0.17640297582660347)
 Hyperplane([0.641187, 0.682606, 0.237959], 0.39354420502349097) 
 Hyperplane([0.694397, 0.860859, 0.690581], 0.8224045176340153)  
 Hyperplane([0.389669, 0.333458, 0.358392], 0.07703612448533725) 

Notice this is 10-element vector whose elements are hyperplanes !!

Let's see if a random point is above or below these hyperplanes.

In [24]:
p = randn(3)

3-element Array{Float64,1}:
  0.7712974179098834
 -0.4635087906725623
 -1.4717581686271488

In [25]:
d.( [p] , hyperplanes)

10-element Array{Float64,1}:
 -1.0104266484557254  
  2.6288289753047867  
 -0.4388137755043886  
  0.38714072479597544 
 -0.2312012145088201  
  1.530631982468101   
 -0.8923489948073887  
  0.22920655807674362 
 -0.044015976495888225
 -0.4865701019195739  

or maybe more readable

In [26]:
[  d(p, h) for h ∈ hyperplanes ]

10-element Array{Float64,1}:
 -1.0104266484557254  
  2.6288289753047867  
 -0.4388137755043886  
  0.38714072479597544 
 -0.2312012145088201  
  1.530631982468101   
 -0.8923489948073887  
  0.22920655807674362 
 -0.044015976495888225
 -0.4865701019195739  